
services:
  - type: web
    name: vokabeltrainer-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
